CLIENTS_DATA_RAW_PATH = 'raw_data/dataset_one.csv'
DETAILS_DATA_RAW_PATH = 'raw_data/dataset_two.csv'
OUTPUT_PATH = 'client_data/output.csv'
LOGS_PATH = 'logs/data_processing.log'
LOGGER_NAME = 'Data Processing Log'
